name: chatconnect
publish_to: 'none'
description: ChatConnect mobile app
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.4.0
  firebase_auth: ^5.1.2
  firebase_messaging: ^15.0.4
  flutter_contacts: ^1.1.7
  permission_handler: ^11.3.1
  socket_io_client: ^3.0.2
  dio: ^5.5.0+1
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  file_picker: ^8.1.2
  image_picker: ^1.1.2
  flutter_webrtc: ^0.11.7
  google_fonts: ^6.2.1
  animations: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true